### ISSUE TITLE
Java API `createCommittableOffsetBatch` should accept `Committable`

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#1020]
The Java API `createCommittableOffsetBatch` requires a list of `CommittableOffset` where it should allow `Committable` (as the Scala API does in `apply`)
https://github.com/akka/alpakka-kafka/blob/086c6056dc3b3cdafd90a8ce4ed906fe298e6eb7/core/src/main/scala/akka/kafka/ConsumerMessage.scala#L184

https://github.com/akka/alpakka-kafka/blob/086c6056dc3b3cdafd90a8ce4ed906fe298e6eb7/core/src/main/scala/akka/kafka/ConsumerMessage.scala#L166

Changing this is almost binary-compatible as type parameter for `List` is not part of the message signature, and `Committable` is wider than `CommittableOffset`.

**Comment by jewertow** [comment]
I will fix it.

**Comment by seglo** [comment]
Fixed in #1033
