### ISSUE TITLE
plainPartitionedManualOffsetSource hangs if a rebalance occurs while loading offsets

### ISSUE THREAD

**Issue by gabrielreid** [akka/alpakka-kafka#1027]
### Versions used 

Akka version:  2.0.0 and 2.0.1

### Expected and Actual Behavior 

It appears that partitions can be completely omitted from the output of `Consumer.plainPartitionedManualOffsetSource` if the loading of offsets is still in progress during a rebalance.

The scenario in question is as follows, in a setup with a topic 2 partitions:
1. Consumer A starts up, and is assigned partitions 0 and 1, and starts asynchronously loading the offsets for these partitions
2. Consumer B starts up
3. Consumer A gets a partition revoke for partitions 0 and 1
4. Consumer A gets a partition assignment for partition 0, and starts asynchronously loading the offsets
5. Consumer B gets a partition assignment for partition 1, and starts asynchronously loading the offsets
6. The loading of offsets for Consumer A from step 1 completes
7. The loading of offsets for Consumer B from step 5 completes
8. The loading of offsets for Consumer A from step 4 completes

After this sequence of events, it is _expected_ that Consumer A has a single running source that provides elements from partition 0,
and Consumer B has a single running source that provides elements from partition 1.

What currently happens is that Consumer A does not receive a single source, while Consumer B does receive a single source for partition 1. This means that no elements are processed for partition 0. However, it is still internally assigned to Consumer A (in a paused state), so it also doesn't get rebalanced.

The end result is also the same if the two offset-loading Futures for Consumer A complete in the reverse order.

This is a significant problem in our situation, where we're loading a snapshotted partition state that also contains the offset when a partition is assigned. We're also starting up multiple consumers at (nearly) the same time, which results in exactly the behavior above. Even if 
offset loading is quite quick, there's still always a chance of running into this situation.

I've got some test cases to reproduce this and a proposed fix which I'll put in a PR.

**Comment by seglo** [comment]
Thanks for reporting this issue.  After looking at your PR I can see how the scenario you document could arise.  I think the easiest way to resolve this issue is to create a new `AsyncCallback` `onOffsetsFromExternalResponse`, that's invoked with the response from `getOffsetsFromExternal(assigned)`.  In that callback, we can filter partitions out of the offset map returned with what is currently assigned.  We'll know what's currently assigned because `partitionAssignedCB` would have been called concurrently while waiting for the external offset `Future`.

**Comment by seglo** [comment]
Oh, I see you did create a PR on `akka/alpakka-kafka` too.

**Comment by gabrielreid** [comment]
@seglo thanks for the tip on defining a new `AsyncCallback`. I've created a new PR with this approach (and the same tests) at #1029.

**Comment by seglo** [comment]
Fixed in #1029
