### ISSUE TITLE
Messages can be repeated or dropped after a rebalance with manual offset source

### ISSUE THREAD

**Issue by gabrielreid** [akka/alpakka-kafka#1036]
### Versions used 

Verified with current HEAD of master (12cb05620369353f457842cc15606f42a0bb8ccb)

### Expected Behavior

When using `Consumer.plainPartitionedManualOffsetSource`, it is expected that a single contiguous stream of records will be passed through for a given partition as long as the partition remains assigned to a single consumer process.

### Actual Behavior

Depending on whether there are (also) manual commits in Kafka, or what the consumers `auto.offset.reset` specifies, a given consumer may receive a large section of duplicate messages, or miss many messages after a rebalance.

This bug was largely introduced by the final fix that was introduced for #1027 (so it's not yet in a released version).

The sequence of events for this bug are:
1. A consumer is assigned partition 0 and partition 1, using external offsets with `Consumer.plainPartitionedManualOffsetSource`
2. At the kafka API level, a rebalance occurs, so partition 0 and partition 1 are revoked
3. As part of the same rebalance, partition 0 is again assigned to the consumer
4. alpakka-kafka requests the external offsets to seek to for partition 0
5. alpakka-kafka discards the retrieved offsets, and either seeks to the latest, earliest, or kafka-managed commit offset (depending on the consumer configuration and/or existence of kafka-managed commits)
6. The consumer either misses a large block of records or skips a large block of records

The issue introduced by the fix for #1027 was to discard external offsets for already-owned partitions after a rebalance (this was to deal with slow-loading or out-of-order loading of offsets).

There's also the additional issue of buffered records being played back in this situation, but as that's a somewhat separate issue (which has been present much longer) I'll log it in a separate PR.

I'll add a PR for this ticket that includes a test case to show the problem and a proposed fix.

**Comment by gabrielreid** [comment]
PR #1037 added with a fix and a test that fails without the fix

**Comment by seglo** [comment]
Fixed in #1037
