### ISSUE TITLE
Drain partial offset commit batches when an upstream failure occurs

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#1039]
### Short description

Flush partially batched offset commits when an upstream failure occurs.

### Details

The current `Committer.flow` implementation uses a `groupWeightedWithin` to batch records using criteria specified in `CommitterSettings`. If an upstream failure occurs we would want to commit the inflight batch to the `KafkaConsumerActor` so that it can be committed during the shutdown process.

Assuming the upstream error isn't Kafka connection related and the stream has the time to shutdown we can ensure that as much of the batch as possible is committed to Kafka so that we don't need to replay those messages when the stream starts back up.

See the discussion in #1032 for the motivation behind this feature request.

**Comment by ennru** [comment]
Thank you @sdudzin for bringing up the discussion in #1032.
This sounds like a good idea for a generic solution. I guess this would require a new internal `Commit` message which triggers an immediate `poll`.

**Comment by sdudzin** [comment]
Since there are 2 messages that are sent (`Commit` and `CommitWithoutReply`) would it make sense to add a flag to both (like `immediateCommit` or `flush`) to them to avid having maintain 2 more message types?

Another thing to consider do we want to make this default behaviour or enable behind a feature flag?

I could come up with a draft implementation of the flow part if that's ok.

**Comment by seglo** [comment]
> Since there are 2 messages that are sent (`Commit` and `CommitWithoutReply`) would it make sense to add a flag to both (like `immediateCommit` or `flush`) to them to avid having maintain 2 more message types?

Yes, `flush` sounds good to me.

> 
> Another thing to consider do we want to make this default behaviour or enable behind a feature flag?

I think a feature flag makes sense.  I also think making it the default case makes sense.  The only concern I have is that secondary exceptions from the Kafka Consumer might get swallowed up, but I suppose this is an existing issue since the `KafkaConsumerActor` will attempt to commit on shutdown anyway.

> 
> I guess we could still use `groupWeightedWithin` but not for batch definition but to be able to cutoff failures from proper flow elements..
> 

I'm not sure what you mean.

> I could come up with a draft implementation of the flow part if that's ok.

That would be excellent.  Thanks @sdudzin!

**Comment by ennru** [comment]
For the specific implementation in `Producer.committableSink` this shouldn't be too hard to implement. I'll look into it.

**Comment by sdudzin** [comment]
Well since CommittingProducerSinkStage seems to be doing it's own batching I mostly kept backwards compatibility on api level.

**Comment by sdudzin** [comment]
You can follow the progress here https://github.com/akka/alpakka-kafka/pull/1058

**Comment by sdudzin** [comment]
Most work left sits in `KafkaConsumerActor` I can have a look at it as well if that's ok.

**Comment by ennru** [comment]
Thank you for putting up the WIP PR. `CommittingProducerSinkStage` already triggers the commit on upstream failure, but it would need the flush flag to tell the consumer actor to trigger the commit immediately.

**Comment by ennru** [comment]
Fixed with #1058
