### ISSUE TITLE
Producer.committableSink doesn't correctly track multi-messages

### ISSUE THREAD

**Issue by gabrielreid** [akka/alpakka-kafka#1040]
### Versions used 

alpakka-kafka 2.0.0

### Expected Behavior

Using `Producer.committableSink` with multi-messages should function in essentially the same way as with single messages, in that messages being successfully sent to the producer should result in the appropriate commits being performed.

### Actual Behavior

Very similarly to the issue with pass-through messages reported in #1021, there is a bug in the internal bookeeping of the number of outstanding commits for multi-messages with `Producer.committableSink`. 

This causes the stream to hang on upstream failures, as well as hanging when there is an attempt to cleanly shut it down via `DrainingControl.drainAndShutdown`.

I'll add a PR with a test that demonstrates the bug, as well as the fix.

**Comment by ennru** [comment]
Fixed with #1041
