### ISSUE TITLE
Incorrect bookkeeping of outstanding produce requests on produce failures

### ISSUE THREAD

**Issue by gabrielreid** [akka/alpakka-kafka#1042]
### Versions used 

alpakka-kafka 2.0.1

### Expected Behavior

When an alternative supervision strategy is used with `Producer.committableSink`, a producer failure should just be ignored and not have further impact on the behavior of the stream (i.e. the stream should still commit outstanding offsets when stopped).

### Actual Behavior

The internal bookkeeping for the number of outstanding produce requests is not correctly updated on a Producer failure. This results in no automatic commit occurring when the source of the stream completes, meaning the stream will stay open until a time-based commit occurs (which could be a very long time, depending on the commit settings)

I noticed this while going through related code while investigating the cause of #1040 

I'll add a PR with a test that demonstrates the failure and a fix.

**Comment by ennru** [comment]
Fixed with #1043
