### ISSUE TITLE
Issue the commit offset first when a message is fully processed

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#1060]
### Short description

Create a flow or other helper, which can help to commit an offset when a message is fully processed even when it leads to multiple messages.

### Details

In many situations, a single consumed message leads to many messages downstream and the offset should be committed only when the last message of those messages is processed successfully.

This is a bit related to `ProducerMessage.multi`, but a more generic case when we don't know the number of downstream messages created from a single message (eg. when using `flatMapConcat`).

One idea to solve this would be to offer a flow which collects the offsets and emits an offset only when a new offset for that topic-partition is received or the stream is completed. Before seeing a later offset it would just emit `CommittableOffsetBatch.empty`.

**Comment by seglo** [comment]
Adding some notes from an offline discussion.

* Adding support to Akka Streams `FlowWithContext` through `flatMapConcat` to let users choose a strategy for creating a context in 1:M situations would be a powerful generic solution.
* As we experiment with enabling tracing it may be possible to use span metadata to determine boundaries.

**Comment by seglo** [comment]
I'm going to explore an API for `flatMapConcat` upstream first.  When that's in place Alpakka Kafka could provide a offset context strategy that indicates the boundaries of the transformed elements.

**Comment by RayRoestenburg** [comment]
@seglo I'm assuming you'll also look at `mapConcat`, right?

**Comment by seglo** [comment]
@RayRoestenburg Yes, in fact I'll experiment using that instead.

**Comment by ennru** [comment]
Implemented in #1093
