### ISSUE TITLE
add getCommittedOffsets() in MetadataClient

### ISSUE THREAD

**Issue by francisdb** [akka/alpakka-kafka#1076]
Since 

`Consumer#committed(TopicPartition partition, Duration timeout)` 

is deprecated in favor of 

`Consumer#committed(Set<TopicPartition> partitions, Duration timeout)`

the alpakka metadata client should probably also provide such method.

**Comment by epalace** [comment]
That was just added yesterday: https://github.com/akka/alpakka-kafka/pull/1073

**Comment by francisdb** [comment]
@epalace great job!
