### ISSUE TITLE
Testkit: Add to ProducerResultFactory ProducerMessage.PassThroughResult helper

### ISSUE THREAD

**Issue by sebarys** [akka/alpakka-kafka#1097]
Hello everyone,

I've created tiny PR to add in `ProducerResultFactory` method that will allow create `ProducerMessage.PassThroughResult` for tests purposes
https://github.com/akka/alpakka-kafka/pull/1096

Thanks for checking in advance :)

**Comment by ennru** [comment]
Fixed with #1096
