### ISSUE TITLE
Upgrade to Kafka 2.6.0 client

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#1098]
Now that [Kafka 2.5.0 is released](https://kafka.apache.org/downloads#2.5.0) Alpakka Kafka should check if we there is anything in particular to adapt to.

Kafka dropped Scala 2.11 which doesn't affect the client library, but the Embedded Kafka will not be able to work with Scala 2.11 anymore.

See https://github.com/akka/alpakka-kafka/issues/1012

**Comment by ennru** [comment]
[Kafka 2.6.0 is released](https://kafka.apache.org/downloads#2.6.0)

https://downloads.apache.org/kafka/2.5.0/RELEASE_NOTES.html
https://downloads.apache.org/kafka/2.6.0/RELEASE_NOTES.html

**Comment by seglo** [comment]
I did a quick scan and I don't see any changes in 2.5 or 2.6 that change the basic behaviour of the consumer that we use. :heavy_check_mark:
