### ISSUE TITLE
(Global / ssExtractRepository) java.lang.NoClassDefFoundError: net/aichler/jupiter/api/JupiterTestCollector$Item

### ISSUE THREAD

**Issue by liaolunhui** [akka/alpakka-kafka#1105]
### Versions used 

Akka version: 

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

### Relevant logs

If you identified a section in your logs that explains the bug or might be important to understand it, please add it.

### Reproducible Test Case

Please provide a PR with a failing test.

If the issue is more complex or requires configuration, please provide a link to a project that reproduces the issue.

**Comment by ennru** [comment]
If you'd like a valuable response, you'd need to explain something about your setup. Please try the forum instead https://discuss.lightbend.com/c/akka/streams-and-alpakka/18
