### ISSUE TITLE
Drop support for Akka 2.5

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#1113]
### Short description

Akka 2.6 has been out for some time now.  In Alpakka Kafka 2.1.0 we should drop support for 2.5 and build with Akka 2.6 only.  This will allow us to simplify the build and release process.

### Details

* Integrate `cluster-sharding` module back into build
* Add _some_ support for using Akka typed APIs.  Internally we can still rely on a classic actor system.

**Comment by dhoepelman** [comment]
Just a chime in, my company is running largely on Play 2.7 because play(-json) 2.8 contains a major breaking change for us, so that also means akka 2.5. Play 2.8 also isn't out for that long (dec 2019)

**Comment by raboof** [comment]
> my company is running largely on Play 2.7 because play(-json) 2.8 contains a major breaking change for us, so that also means akka 2.5

Thanks for bringing that up!

Because of Akka's [binary compatibility](https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html), using Play 2.7 with Akka 2.6 should work just fine. Did you run into any problems with that update?
