### ISSUE TITLE
Drop testkit support for Embedded Kafka

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#1114]
### Short description

Bundling embedded Kafka in the testkit can make it challenging to support new versions of Kafka in Alpakka Kafka as the release cycle lags Apache Kafka.  When we included Embedded Kafka on the classpath it can conflict with the core Kafka client dependency and its dependency tree.  Embedded Kafka with Schema Registry also relies on Confluent Platform images which typically lags the Apache Kafka release by 1-2 months and doesn't always support the same Scala versions.

### Details

* Update any remaining tests to use testcontainers instead of Embedded Kafka
* Re-factor `SerializationSpec` to use testcontainers.

**Comment by seglo** [comment]
@ennru All that remains for this work is reorganizing docs. #1209 replaces the last of the tests that depend on embedded-kafka (except for docs snippets).

**Comment by seglo** [comment]
If we decide not to drop it, then I think we should at least isolate the docs snippet tests in another project so they don't interfere with the rest of the tests.

**Comment by ennru** [comment]
Kafka core inlines the Scala library which hinders to use Embedded Kafka with different Scala patch versions than the ones Kafka is compiled against.

This definitely decides that we drop Embedded Kafka support from the Alpakka Kafka testkit.

See https://github.com/akka/alpakka-kafka/pull/1212 and https://github.com/embeddedkafka/embedded-kafka/issues/202
