### ISSUE TITLE
Upgrade to ScalaTest 3.1.x

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#1158]
For the next minor release, I suggest upgrading the testkit (and the tests) to ScalaTest 3.1.x.

Going all the way to ScalaTest 3.2 with the new dependency structure can wait. People choosing 3.2 should be able to do that if Alpakka Kafka uses 3.1.x.

See https://www.scalatest.org/release_notes/3.2.0 and https://www.scalatest.org/release_notes/3.1.0

Refs #1156

**Comment by raboof** [comment]
> People choosing 3.2 should be able to do that if Alpakka Kafka uses 3.1.x.

I'm not sure this is guaranteed to be true (https://www.scalatest.org/release_notes/3.2.0 claims it is not binary compatible), though it might still be true in practice.

**Comment by ennru** [comment]
Alpakka Kafka should follow the versions chosen in Akka.
See https://github.com/akka/akka/issues/29368

**Comment by ennru** [comment]
Fixed with #1207
