### ISSUE TITLE
Adapt `AlpakkaKafkaContainer` to Testcontainers 1.15

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#1225]
The upcoming Testcontainers 1.15 version brings important improvements to the framework.
https://github.com/testcontainers/testcontainers-java/releases

As `AlpakkaKafkaContainer` replaces `KafkaContainer` it needs to be updated with the latest changes from Testcontainers. Specifically, https://github.com/testcontainers/testcontainers-java/pull/3293 adapts it to work with the Kafka broker bundled in Confluent Platform 6.0.0.

**Comment by agemooij** [comment]
Any idea when this issue can be fixed and released?

All our Kafka tests started failing on my machine after I innocently said yes to a new stable release (2.5.0.0) of the docker for Mac distro. This triggered [an issue in testcontainers](https://github.com/testcontainers/testcontainers-java/pull/3159) that causes it to fail catastrophically.

I'll try downgrading my docker client to pre-2.4 for now but it would be great if this incompatibility could be fixed ASAP.

**Comment by ennru** [comment]
With #1257 Alpakka Kafka uses Testcontainers 1.15.0.

@agemooij I would expect overriding the Testcontainers version in 3.0.0-M1 works. We'd want to progress a bit more before releasing M2.

**Comment by agemooij** [comment]
OK, thanks! I'll try that. The Docker for Mac downgrade worked for me as well but I assume quite a few people will start running into this as they upgrade their systems so probably good to clearly mention it in the release notes and perhaps even as a known issue for the 2.0 releases.

**Comment by agemooij** [comment]
@ennru I guess you meant the 2.1.0-M1 release? Or are you going to relabel it to 3.0 for M2?

**Comment by ennru** [comment]
My bad, I mixed things up with main Alpakka. 
The upcoming Alpakka Kafka version is 2.1.0.
