### ISSUE TITLE
Simulate downed broker with testcontainers in ReconnectSpec

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#1233]
### Short description

As part of the effort to remove embedded-kafka (#1114) I rediscovered a test that simulates a broker being lost to assure that Alpakka Kafka reconnects gracefully and completes consuming messages. This was fairly trivial to do with Embedded Kafka, but is a challenge to recreate with testcontainers.

### Details

Ideally we would simply stop and start the container again, but `testcontainers-java` will implicitly stop and remove state when stop any containers.  Even if we could stop the container without removing state, bringing it back online will still generate a random host port which won't be known by Alpakka Kafka when it's trying to reconnect.  There's `testcontainers-java` issue for this functionality that discusses some of the challenges https://github.com/testcontainers/testcontainers-java/issues/606.

Revised details from https://github.com/akka/alpakka-kafka/pull/1229#discussion_r505353715 to discuss what I've tried so far:

* I'm able to pause and unpause the broker containers in place of embedded-kafka stop and start. This doesn't appear to kill any active connections. When I enable Kafka `NetworkClient` logs I can see with the previous embedded-kafka impl. a disconnect would occur.

i.e.)

```
      // pause Kafka brokers
      this.brokerContainers.foreach(c => c.getDockerClient.pauseContainerCmd(c.getContainerId).exec())
      // unpause Kafka brokers and produce another round
      this.brokerContainers.foreach(c => c.getDockerClient.unpauseContainerCmd(c.getContainerId).exec())
```

* I can disconnect and reconnect the network to broker containers. This will force any active connections to close, but when the network is reattached the host port is different. Testcontainers will always generate a random host port and there doesn't appear to be a way around this. https://www.testcontainers.org/features/networking/ .

i.e.)

```
	  // detach network
      this.brokerContainers
        .foreach(
          c =>
            c.getDockerClient
              .disconnectFromNetworkCmd()
              .withForce(true)
              .withContainerId(c.getContainerId)
              .withNetworkId(c.getNetwork.getId)
              .exec()
        )

      // re-attach network
      this.brokerContainers
        .foreach(
          c =>
            c.getDockerClient
              .connectToNetworkCmd()
              .withContainerId(c.getContainerId)
              .withNetworkId(c.getNetwork.getId)
              .exec()
        )
```

Some other ideas

* Use something like `iptables` or other networking tools to disable connections in the running container itself, but I can't find any of the usual programs in the image to do this (`iptables`, `route`) or even network interface commands. Since `confluentinc/cp-kafka:6.0.0` the image now defaults to a non-root user `appuser`, so I can't install any tools anyway unless I rebase the image.

* Stop and start the broker process within the running container. This should do the trick, but it will require some work to update the container run command to support it.

**Comment by seglo** [comment]
Summoning @bsideup in case he has any suggestions.

**Comment by bsideup** [comment]
@seglo if pause/unpause works, I'd go this way, as the most "essential" :)

If it doesn't, my second suggestion would be to kill the process inside the container and then call `/testcontainers_start.sh` again.

Last but not least, you can change the user back to `root` even if the image defines a custom user and call the network interface commands, at least Docker allows that.

**Comment by seglo** [comment]
Thanks for the reply @bsideup.  Pausing doesn't work, unfortunately, unless I wait for the client to timeout.

> Last but not least, you can change the user back to `root` even if the image defines a custom user and call the network interface commands, at least Docker allows that.

Is this something you can do ad-hoc with testcontainers-java/docker-java?

**Comment by bsideup** [comment]
@seglo yes, see `withCreateContainerCmdModifier` and `CreateContainerCmd#withUser(String)`
