### ISSUE TITLE
Commits should be retried on RebalanceInProgressException

### ISSUE THREAD

**Issue by altomch** [akka/alpakka-kafka#1243]
Kafka-client's committing behavior was changed since v2.5.0 ([Release notes](https://kafka.apache.org/documentation.html#upgrade_250_notable)):
> When RebalanceProtocol#COOPERATIVE is used, Consumer#poll can still return data while it is in the middle of a rebalance for those partitions still owned by the consumer; in addition Consumer#commitSync now may throw a non-fatal RebalanceInProgressException to notify users of such an event, in order to distinguish from the fatal CommitFailedException and allow users to complete the ongoing rebalance and then reattempt committing offsets for those still-owned partitions.

So `RebalanceInProgressException` ([OffsetCommitCallback](https://github.com/apache/kafka/blob/2.6/clients/src/main/java/org/apache/kafka/clients/consumer/OffsetCommitCallback.java#L41)) should be retried on committing.

### Versions used 
Alpakka-Kafka version: 2.1.0-M1
Akka version: 2.6.10
Kafka-client version: 2.6.0

### Expected Behavior

Commits which failed with `RebalanceInProgressException` should be retried on next poll attempt after rebalance.

### Actual Behavior

`RebalanceInProgressException` propagated to Committer stage

**Comment by ennru** [comment]
Thank you for reporting this important change and suggesting a change.

Is this behaviour dependent on the Kafka broker version?
Will the client show the `RebalanceInProgressException` even when connected to pre-2.5 brokers?

**Comment by altomch** [comment]
I think it's related to client only, I've seen this issue on brokers v2.4.1.
Here PR from kafka's repo: [KAFKA-8421](https://github.com/apache/kafka/pull/7312/files)

**Comment by seglo** [comment]
Fixed in #1247
