### ISSUE TITLE
Consumer: Add `retry.backoff.ms` to `reference.conf`

### ISSUE THREAD

**Issue by janjaali** [akka/alpakka-kafka#1358]
### Short description

Add the `retry.backoff.ms` to the consumer config in `reference.conf` so that clients that use the default values do not run in very very tight restart-loop (i.e. the default value is 100ms) and so that clients can overwrite that values easy-ish in their `application.conf`'s.

### Details

 Add `retry.backoff.ms` to `reference.conf` and use it in `ConsumerSettings.scala` as we do for e.g. the `poll-interval`.

Relates to: <https://kafka.apache.org/documentation/#consumerconfigs_retry.backoff.ms>

**Comment by ennru** [comment]
You can add any Kafka Consumer settings in the `kafka-clients` section in the application.conf.
https://doc.akka.io/docs/alpakka-kafka/current/consumer.html#programmatic-construction

Or use the `consumerSettings.withProperty` in your code.

**Comment by janjaali** [comment]
Oh did not know that there is a built-in parser for Kafka client properties for the application.conf `kafka-clients` node. Thanks for pointing that out 👍
