### ISSUE TITLE
Have to ability to configure the schema registry in the test kit

### ISSUE THREAD

**Issue by yuvalshi0** [akka/alpakka-kafka#1479]
### Short description
Using the feature "Testing with a Docker Kafka cluster" in the testkit, there is the option the further configure the kafka and the zookeeper using the method `.withConfigureKafka(...)` (for example) (https://doc.akka.io/docs/alpakka-kafka/current/testing-testcontainers.html#settings), but I see there is no option to do the same with the schema registry.

### Details

Add a method to further configure the schema registry i.e. `.withConfigureShemaRegistry(...)`
(I can try to make a PR if this request sound reasonable)

**Comment by ennru** [comment]
Sure, sounds good to even configure the schema registry. We're looking forward to your PR.
