### ISSUE TITLE
DrainingControl.isShutdown memory leak

### ISSUE THREAD

**Issue by ilinandrii** [akka/alpakka-kafka#1642]
### Versions used 
2.0.5
master

Akka version: 
2.5.32

### Expected Behavior
Calls to `DrainingControl.isShutdown` method don't create additional future callbacks that occupy memory and in a long run for infinite streams lead to OOM

### Actual Behavior
I'm using `DrainingControl.isShutdown().isCompleted()` for consumer health checks. 
Health check calls lead to corresponding `isShutdown` calls on all running consumers, which in turn create [new future callbacks](https://github.com/akka/alpakka-kafka/blob/8670cf9f2f767bad34e09ade7836a2e76b7f2243/core/src/main/scala/akka/kafka/scaladsl/Consumer.scala#L122) with `.flatMap`.  
The number of callbacks constantly growth and because all of my consumers are infinite streams those callbacks are never resolved and occupy heap until OOM is reached after a very long run.
I've workaround this by caching first call on `isShutdown` and calling `isCompleted` on returned future on each health check call, however it would be nice to have it fixed in a library.

**Comment by ennru** [comment]
Thank you for reporting this. Recreating the future should not be necessary and must be avoided.
Would you be in a position to suggest a fix?
