### ISSUE TITLE
Document how to do test pipelines 

### ISSUE THREAD

**Issue by drewhk** [akka/alpakka-kafka#228]
i.e. how to stub out Kafka Sources and Sinks, check for proper commits, etc.

**Comment by nezabelej** [comment]
Is there something new about this issue yet ? If not documented yet, is there some example of testing Reactive Kafka ?
For example, I am trying to test my code which is very similar to http://doc.akka.io/docs/akka-stream-kafka/current/producer.html (Producer as a flow).
I get ConsumerMessage as a Source, manipulate it (Flow) and then pass it to the Sink.
So I need something like this ( http://doc.akka.io/docs/akka/current/java/stream/stream-testkit.html ), but for Reactive Kafka.

**Comment by ennru** [comment]
Fixed with #621
