### ISSUE TITLE
Add API for consuming Future[ProducerMessage.Result] from the ProducerStage

### ISSUE THREAD

**Issue by iravid** [akka/alpakka-kafka#250]
Currently, the futures coming out of the `ProducerStage` are processed through a `mapAsync(identity)`. This causes exceptions thrown to be handled through the stream supervision.

Dealing with errors from the producer is at times too simplistic through the `Supervision.Decider` interface; for example, if one would like to convert a failed request to a custom ADT, there is currently no way (I can think of, at least :-)) to run a `.recover` on the result.

I would like to suggest adding an API that exposes the `Future[ProducerMessage.Result]` from the `ProducerStage`. 

If this seems too unconstrained, perhaps an alternative is to for the user to provide a `Future[ProducerMessage.Result] => Future[Out]` or a `Try[ProducerMessage.Result] => Try[Out]`. 

This will allow users to handle the errors in a more value-oriented way.

I'd be happy to submit a PR for this.

**Comment by ennru** [comment]
This is available now. Finally...
https://doc.akka.io/docs/alpakka-kafka/current/send-producer.html
