### ISSUE TITLE
[Consumer] Endless rebalancing

### ISSUE THREAD

**Issue by cchantep** [akka/alpakka-kafka#304]
Using ReactiveKafka 0.16 with Kafka server 0.10.2 (or 0.10.0) for a test application, running several instances of this test app results in endless rebalancing.

This app is managing 190 consumers, across 19 different consumer group, against 12 distinct topics (details bellow).

When one app instance is starting, with 40 partitions per topic, it takes ~1m to get stable assignments on topic partitions for all the workers: long time but could be understandable ...

When two instances of the app are started (same kafka server setup), it goes through an infinite rebalancing loop, not consuming anything (with messages such as `Attempt to heartbeat failed for group ...`, `(Re-)joining ...`, `UNKNOWN_MEMBER_ID ...`).

This test app is just printing data for now, no long processing. I've tried several settings (session.timeout, heartbeat, client.id, ...), but I cannot fix that.

For more details, this app is simulating consumpting by several kinds of worker/processor, with one distinct consumer group per kind.

Some different kinds of worker, and so different consumer groups, could subscribe to a same topic.

The app is so using 19 distinct consumer groups (1 per simulated worker kind), against 12 different topics.

Moreover, per each kind of worker, 10 consumer instances are created and subscribe using the same consumer group to the appropriate topic.

`Main.scala`:

```scala
package tests

import scala.concurrent.Future

import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.kafka.KafkaConsumerActor
import akka.kafka.scaladsl.Consumer

import com.typesafe.config.ConfigFactory

import com.intermarche.ingestion.kafka.{ Connector, KafkaConf }

object Main extends App {
  val kconf = KafkaConf(ConfigFactory.load()).get
  val kafka = new Connector(kconf)

  implicit val system = ActorSystem("Tests")
  implicit val materializer = ActorMaterializer()
  implicit def ec = materializer.executionContext

  val workerMeta = Seq(
    "A" -> "G1",
    "B" -> "G2",
    "C" -> "G3",
    "C" -> "G4",
    "D" -> "G5",
    "D" -> "G6",
    "E" -> "G7",
    "E" -> "G8",
    "F" -> "G9",
    "F" -> "G10",
    "G" -> "G11",
    "G" -> "G12",
    "H" -> "G13",
    "H" -> "G14",
    "I" -> "G15",
    "J" -> "G16",
    "K" -> "G17",
    "L" -> "G18",
    "M" -> "G19",
    "N" -> "G20"
  )

  val workers = //: Traversable[Consumer.Control] =
    workerMeta.flatMap {
      case (topic, group) =>
        (0 until 10).map { id =>
          Worker.reactive(topic, group, id, kafka)
        }
    }

  Runtime.getRuntime.addShutdownHook(new Thread() {
    override def run() {
      workers.foreach(_.shutdown())
    }
  })
}
```

`Worker.scala`:

```scala
package tests

import scala.util.Success

import scala.concurrent.{ ExecutionContext, Future }
import scala.concurrent.duration._

import org.apache.kafka.clients.consumer.{ ConsumerRecord, KafkaConsumer }

import akka.{ Done, NotUsed }
import akka.stream.Materializer
import akka.stream.scaladsl.{ Flow, Keep, RunnableGraph, Sink, Source }

import akka.kafka.ConsumerMessage.{ CommittableMessage, CommittableOffsetBatch }
import akka.kafka.scaladsl.Consumer

import io.circe.{ Json, parser }

import com.intermarche.ingestion.kafka.{ Service, KafkaConf }

object Worker {
  val batchSize = 250
  val commitParallelism = 20

  def batching() = CommittableOffsetBatch.empty

  def reactive(
    topic: String,
    group: String,
    workerId: Int,
    kafka: Service
  )(implicit m: Materializer): Consumer.Control = {
    implicit def ec = m.executionContext
    def source = kafka.committablePartitionedSource(topic, group)

    source.toMat(Sink.ignore)(Keep.left).run()
  }
}
```

**Comment by cchantep** [comment]
Seems due to https://github.com/akka/reactive-kafka/blob/6174512656db74f46eb738638b41987d28c0fbe8/core/src/main/resources/reference.conf#L80

**Comment by tavoaqp** [comment]
Hi, I'm also having this problem, did you get to solve it?

**Comment by ennru** [comment]
Did you try to reuse the Kafka Consumer actor as described in https://doc.akka.io/docs/akka-stream-kafka/current/consumer.html#sharing-the-kafkaconsumer-instance ?

**Comment by tavoaqp** [comment]
Hi @ennru , I actually solved this some time ago. The problem was that the partition assignment algorithm was always using the same partition because all my keys had the same value. What I did was to write an algorithm to equally distribute messages to all partitions.

**Comment by 2m** [comment]
Aha! Good to know that you were able to solve this.
