### ISSUE TITLE
Publish snapshot documentation

### ISSUE THREAD

**Issue by raboof** [akka/alpakka-kafka#335]
We currently don't publish the latest documentation from master to http://doc.akka.io/docs/akka-stream-kafka/ , that would be nice to add to travis.

**Comment by patriknw** [comment]
We should probably align the release process here with projects like Alpakka, i.e. release from Travis and publish documentation at developer.lightbend.com. That will also give us snapshot (latest) docs.

**Comment by raboof** [comment]
That sounds sensible, moving away from the manually-managed `doc.akka.io` to something more reproducible.

If techhub doesn't support `.htaccess` for redirects, canonical headers and such kinds of features perhaps we should add them there when we need them.

**Comment by 2m** [comment]
Snapshot artifacts are now being published after every merge to master by travis. They can be found here: https://bintray.com/akka/snapshots/alpakka-kafka

We still need to add a mention of snapshots to the documentation.

**Comment by ennru** [comment]
We mention the availability of snapshots since a while back https://doc.akka.io/docs/alpakka-kafka/current/snapshots.html

Now only publishing docs for snapshots is missing.

**Comment by 2m** [comment]
Fixed with #662

https://doc.akka.io/docs/alpakka-kafka/snapshot/snapshots.html
