### ISSUE TITLE
Serialization exception not surfaced in "Consumer actor terminated" exception

### ISSUE THREAD

**Issue by rrodseth** [akka/alpakka-kafka#356]
We ran into a situation in which a topic contained a message containing an invalid schema id.

The Kafka Avro deserializer complained as follows:

Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 4
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403

Rather than resulting in something we could handle with Supervision (we'd like to skip over this element), instead the consumer actor was terminated, and the exception is very generic and contains no cause.

In the onFailure handler of the materialized Future[Done], we saw:

Caused by: java.lang.Exception: Consumer actor terminated
at akka.kafka.internal.SubSourceLogic$SubSourceStage$$anon$1$$anonfun$preStart$2.apply(SubSourceLogic.scala:150) 

At that point there is no way to skip the element by resuming, and the stream is stuck because it is stopped (and restarted by our host actor) with no offset committed. The "Consumer actor terminated" exception has no cause value.

Obviously we are working to prevent such invalid messages, but would like to be able to handle them with supervision. Also posted to akka-user.
https://groups.google.com/forum/#!topic/akka-user/WP-CSoyuIaA

**Comment by patriknw** [comment]
I guess one could create the consumer actor with a parent supervisor actor that would use Resume for this exception type. However, that is probably rather inconvenient to use so we should perhaps allow for a setting that would instruct the consumer actor to catch, log and resume such exception.
