### ISSUE TITLE
Trouble integrating with BroadcastHub

### ISSUE THREAD

**Issue by mrwillis** [akka/alpakka-kafka#486]
Hi,

I'm trying to use `reactive-kafka` with a broadcast hub. I'm using Play! and the idea is I want to have one WebSocket connection for each client directly to a kafka topic. The issue I'm running into is even though I'm using a `BroadcastHub`, it seems like my clients are fighting for messages. Here are some logs to explain:

> [info] m.SocketIOEngineProvider - Sink ignore 111694
> [info] m.SocketIOEngineProvider - Sink ignore 111695
> [info] m.SocketIOEngineProvider - Sink ignore 111696
> [info] m.SocketIOEngineProvider - Sink ignore 111697
> [info] m.SocketIOEngineProvider - Sink ignore 111698
> [info] m.SocketIOEngineProvider - Sink ignore 111699
> [info] m.SocketIOEngineProvider - d392a846-46f1-4409-90ac-841e7e723576 111700
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [info] m.SocketIOEngineProvider - Sink ignore 111701
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [info] m.SocketIOEngineProvider - Sink ignore 111702
> [info] m.SocketIOEngineProvider - d392a846-46f1-4409-90ac-841e7e723576 111703
> [info] m.SocketIOEngineProvider - Sink ignore 111704
> [info] m.SocketIOEngineProvider - Sink ignore 111705
> [info] m.SocketIOEngineProvider - Sink ignore 111706
> [info] m.SocketIOEngineProvider - Sink ignore 111707
> [info] m.SocketIOEngineProvider - Sink ignore 111708
> [info] m.SocketIOEngineProvider - Sink ignore 111709
> [info] m.SocketIOEngineProvider - d392a846-46f1-4409-90ac-841e7e723576 111710
> [info] m.SocketIOEngineProvider - Sink ignore 111711
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [info] m.SocketIOEngineProvider - d392a846-46f1-4409-90ac-841e7e723576 111712
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)
> [warn] a.k.KafkaConsumerActor - RequestMessages from topic/partition Set(topic-0) already requested by other stage Set(topic-0)

As you can see, it's split up between the consumers. What I am doing that results in this behaviour is the following. Globally I create a `BroadcastHub` like so:

```scala
  private val producer
    : Source[ConsumerRecord[String, String], Consumer.Control] =
    Consumer
      .plainExternalSource[String, String](
        kafkaConsumerActor,
        Subscriptions.assignment(new TopicPartition("topic", 0)))

  private val hub
    : RunnableGraph[Source[ConsumerRecord[String, String], NotUsed]] =
    rawOhlcvProducer.toMat(BroadcastHub.sink)(Keep.right)
```

And then before anyone connects (to ensure the producer is always drained)

   ` hub.run().runWith(Sink.ignore)`

And then every time a client connects:

```scala

        // Source from the kafka broadcast hub that only gets
        // data for this particular kafkaKey
        val graph = hub
          .run()
          .map(record => Json.parse(record.value()).as[ExchangeCandleData]).to(userSink)

        // Start it up!
        val killSwitch = graph.run()
```
I assumed the BroadcastHub would fix this issue, but it seems I need something else? I think someone else had a similar issue here:

https://stackoverflow.com/questions/36348020/kafka-message-to-websocket

Can anyone suggest anything?

Thanks!

**Comment by 2m** [comment]
When you run the hub (`hub.run()`) the materialized value that you get back is `Source[ConsumerRecord[String, String]`. Now whenever this new `Source` is ran, it will be a new branch in the broadcast hub. Therefore when a new client connects, instead of running the hub again, run the source that you got from running the  hub.

As far as I can see you start a new broadcast hub for every new client.
