### ISSUE TITLE
Add wrapper for Metadata requests

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#497]
The new feature to request Kafka Metadata from the internal `KafkaConsumerActor` (see #491) would be even nicer with thin wrappers (javadsl and scaladsl) hiding the `ask` calls and mapping to the correct response types.

**Comment by 2m** [comment]
The wrapper should also have Scala and Java DSLs with appropriate conversions between Java and Scala types and collections.

**Comment by jewertow** [comment]
I will take care of it.

**Comment by jewertow** [comment]
I started working on it but I wonder what return types do expect from the wrapper, e.g. in the case of `EndOffsets` the wrapper should return `Future[Long]` or `Future[Option[Long]]`?

**Comment by ennru** [comment]
With the current `GetEndOffsets(Set[TopicPartition])` the response is `EndOffsets(Map[TopicPartition, Long])`. So I'd expect `Future[Map[TopicPartition, Long]]`.

**Comment by ennru** [comment]
Implemented in #497 by @jewertow
