### ISSUE TITLE
published pom for v0.21 includes compile-scope dependency on docker-client

### ISSUE THREAD

**Issue by schoeneu** [akka/alpakka-kafka#504]
see http://central.maven.org/maven2/com/typesafe/akka/akka-stream-kafka_2.11/0.21/akka-stream-kafka_2.11-0.21.pom

The "it" scope used in the sbt dependency configuration (introduced in https://github.com/akka/alpakka-kafka/commit/ecf11ddd78d237a40f8a560c3a5ee3cd808720eb ) seems to be mapped to the (production) compile scope when you are releasing the artifact.

This pulls the docker-client library as a compile dependency into all projects using alpakka-kafka.

**Comment by 2m** [comment]
Good catch! Will fix it right away.

**Comment by 2m** [comment]
Looks like we stepped on https://github.com/sbt/sbt/issues/1380
