### ISSUE TITLE
NoSuchMethodError using 0.21.1 with com.typesafe.config 1.2.1

### ISSUE THREAD

**Issue by Willem1987** [akka/alpakka-kafka#514]
It seems that the typesafe config requires a TimeUnit to be passed along with the path. The akka.kafka.internal.EnhancedConfig does not conform to this unfortunately.

This causes : 
An exception or error caused a run to abort: com.typesafe.config.Config.getDuration(Ljava/lang/String;)Ljava/time/Duration; 
java.lang.NoSuchMethodError: com.typesafe.config.Config.getDuration(Ljava/lang/String;)Ljava/time/Duration;
	at akka.kafka.internal.EnhancedConfig$.getPotentiallyInfiniteDuration$extension(EnhancedConfig.scala:16)

**Comment by ennru** [comment]
The dependency should be `com.typesafe.config` version 1.3.2 which is brought in by `akka.actor`, you can't use `config` versions before 1.3.0.

**Comment by Willem1987** [comment]
Ah. I'm sorry. I wasn't aware. Another framework we use pushed an old version apparantly.
