### ISSUE TITLE
Doc issue: Consumer and producer examples are not correct/complete

### ISSUE THREAD

**Issue by davideicardi** [akka/alpakka-kafka#515]
I have some problems creating an "hello world" example following your documentation.

The main problem is that **there isn't a concise and easy to follow end-to-end example**.

The other problem is that the code provided for [ConsumerSettings](https://doc.akka.io/docs/akka-stream-kafka/current/consumer.html#settings) and [ProducerSettings](https://doc.akka.io/docs/akka-stream-kafka/current/producer.html#settings) are not correct:

```
val config = system.settings.config
val consumerSettings =
  ConsumerSettings(config, new StringDeserializer, new ByteArrayDeserializer)
    .withBootstrapServers("localhost:9092")
    .withGroupId("group1")
    .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest")
```

```
val config = system.settings.config
val producerSettings =
  ProducerSettings(config, new StringSerializer, new StringSerializer)
    .withBootstrapServers("localhost:9092")
```

Because the `apply` function looks directly for a section `kafka-clients` while the `system.settings.config` contains this section inside `akka.kafka.consumer/akka.kafka.producer`.
See also [this discussion](https://stackoverflow.com/q/50914596/209727).

I'm right or I'm missing something?

thanks

**Comment by ennru** [comment]
Thank you for reporting this. 
You are totally right, you need to pass `config.getConfig("akka.kafka.producer")` to get the same behaviour as when passing the actor system.

**Comment by ennru** [comment]
Oh no, not even that will work as expected. Sorry for the inconsistencies here.
