### ISSUE TITLE
Wrong logic to calculate "Kafka commit took longer than..." warning

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#518]
On receiving a commit message the Kafka Consumer Actor may issue a warning "Kafka commit took longer than *commit-time-warning*".
To calculate the time the commit takes `System.nanoTime()` is used, comparing values from two different threads is not useful. `currentTimeMillis` should be used instead.

[source](https://github.com/akka/alpakka-kafka/blob/988c1b628c47b1faff94ec44093c886ea3243cbf/core/src/main/scala/akka/kafka/internal/KafkaConsumerActor.scala#L474)

**Comment by patriknw** [comment]
> comparing values from two different threads is not useful

Is that really true? What is the authoritative reference?
Across different JVMs it can't be used but within same JVM it's the recommended way to measure durations, AFAIK.


`currentTimeMillis` on the other hand may jump backwards

**Comment by ennru** [comment]
Hm, I consider you more authoritative than my other source... 

Looking at it again, the version where a problem was reported (0.18) did lie about the time units it shows - that is [fixed already](https://github.com/akka/alpakka-kafka/issues/406).
