### ISSUE TITLE
Race condition when getting metrics from consumer

### ISSUE THREAD

**Issue by LMnet** [akka/alpakka-kafka#528]
Hi everybody! I tried to use metrics from the consumer like this (simplified):
```scala
val control = runnableGraph.run()
control.metrics.onComplete { 
  case Success(metrics) =>
    println(metrics)  
  case Failure(e) =>
    println(e)
}
```
And I got an error:
```
java.lang.IllegalArgumentException: Unsupported recipient ActorRef type, question not sent to [null]. Sender[null] sent the message of type "akka.kafka.internal.KafkaConsumerActor$Internal$RequestMetrics$"
```

I tried to debug it and I found, that this error is from this code inside `SingleSourceLogic`:
```scala
override def metrics: Future[Map[MetricName, Metric]] = {
  import akka.pattern.ask
  import scala.concurrent.duration._
  consumer
    .?(RequestMetrics)(Timeout(1.minute))
    .mapTo[ConsumerMetrics]
    .map(_.metrics)(ExecutionContexts.sameThreadExecutionContext)
}
```
When I called `metrics` method, `consumer` variable is still uninitialized. That's because it initialized inside `preStart` block, which could be not finished at the moment when I call `metrics` method. Typical race condition.

**Comment by ennru** [comment]
Thank you for this report, I just stumbled about it today, as well.
