### ISSUE TITLE
Delayed message consumption - alpakka-kafka connector 0.22 

### ISSUE THREAD

**Issue by GnanasoundariSoundarajan** [akka/alpakka-kafka#546]
Hi, 

alpakka-kafka connector version 0.22

After upgrading alpakka-kafka connector version from 0.21.1 to 0.22, I am facing 1min delay in consuming messages. If i keep version as 0.21.1, it consumes message immediately.

0.22: (Delay ~1min)
**message received time in kafka:**
[centos@Kafka_Redis kafka_2.12-0.11.0.2]$ date
**Fri Aug 17 10:15:53 UTC 2018**
[centos@Kafka kafka_2.12-0.11.0.2]$ ./bin/kafka-console-consumer.sh --bootstrap-server <kafka-broker>:9092 --topic <topic0>
{"asset":"A","name":"AutomationSanityTestActionNameA","priority":0,"label":"action","destination":0}

**message received time in application using alpakka 0.22**
**2018-08-17 10:16:53.323**  [app1-akka.actor.default-dispatcher-281] INFO        o.d.c.a.hub.actor.testActor:80 -   Received message

0.21.1: (Delay ~6sec)
**message received time in kafka:**
[centos@Kafka_Redis kafka_2.12-0.11.0.2]$ date
**Fri Aug 17 10:09:58 UTC 2018**
[centos@Kafka kafka_2.12-0.11.0.2]$ ./bin/kafka-console-consumer.sh --bootstrap-server <kafka-broker>:9092 --topic <topic0>
{"asset":"A","name":"AutomationSanityTestActionNameA","priority":0,"label":"action","destination":0}

**message received time in application using alpakka 0.21.1**
**2018-08-17 10:10:04.496** [app1-akka.actor.default-dispatcher-281] INFO        o.d.c.a.hub.actor.testActor:80 -   Received message

**Comment by ennru** [comment]
Interesting.

I can't find anything in the diff that could explain this effect.
https://github.com/akka/alpakka-kafka/compare/v0.21.1...v0.22
Most changes regard the logging.

**Comment by ennru** [comment]
I tried your configuration and your flow implementation, it reads the data immediately - I used `Sink.head` to finish on the first message.
How do the messages get produced?

**Comment by GnanasoundariSoundarajan** [comment]
Thanks for trying out.
Messages are produced using the same connector. Here is the settings.
 kafka {
        producer {
           parallelism = 100
           bootstrap.servers = "<server1>:9092,<server2>:9092, <server3>:9092"
           close-timeout = 30s
           auto.offset.reset = "earliest"
           max.redeliveries = 0
           use-dispatcher = "kafka-dispatcher"
           kafka-clients {
	           retries = 0
               acks = 0
               buffer.memory=67108864
               batch.size=8192
               linger.ms = 2
			   max.in.flight.requests.per.connection = 512
       		}
        }
     }

This message is not getting pushed continuously. Message will be pushed whenever some action needs to be performed by the consuming entity. Its completely on demand. 

I suggest you to monitor by sending messages for a period of time randomly.

**Comment by ennru** [comment]
This is too old to follow up on. I hope you solved it back in the days...
Closing.
