### ISSUE TITLE
Make Integration test Docker setup work on OS X

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#556]
The current Docker setup for the integration tests and benchmarks works on Linux but gets non-workable hostnames on OS X.

**Comment by bsideup** [comment]
Hi! I'm one of Testcontainers ( http://testcontainers.org ) developers and will be happy to help if you decide to use it (FYI we have KafkaContainer) :)

**Comment by ennru** [comment]
@bsideup Thank you for reaching out! Right now we solve this with the hack of adding the OS X Docker internal hostname to `/etc/hosts`
```
127.0.0.1	linuxkit-025000000001
```
We might consider Testcontainers in the future.

**Comment by ennru** [comment]
These tests do now use Testcontainers!
We hope our contribution in https://github.com/testcontainers/testcontainers-java/pull/1984 will be added.

**Comment by bsideup** [comment]
@ennru 

Congratulations! 🎉 

Regarding the contribution - on my list for this weekend ;)
