### ISSUE TITLE
Commit With Metadata

### ISSUE THREAD

**Issue by johnclara** [akka/alpakka-kafka#561]
I would like to add metadata based on the ConsumerRecord with my committed offset.

My goal is to consume a replicated topic in a DR DC starting each consumer from around the time where it left off. My goal is to add the timestamp of the message in ConsumerOffsets and replicate this topic to a DR DC. From this timestamp, I can get an offset close to that of the oldest last read message per GroupTopic in the DR DC during a failover. A ConsumerGroup would read each replicated topic starting from these offsets.

**Comment by johnclara** [comment]
PR is here: https://github.com/akka/alpakka-kafka/pull/562

**Comment by ennru** [comment]
Fixed with #563
