### ISSUE TITLE
Partitioned sources revoke/assign ignore re-assigned partitions

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#570]
#382 reported lost messages on partition reassignment. This was solved (or at least improved) with #462 and #517, by delaying the actual handling of the revoked topic partitions: [SubSourceLogic.partitionRevokedCB](https://github.com/akka/alpakka-kafka/blob/v0.22/core/src/main/scala/akka/kafka/internal/SubSourceLogic.scala#L124-L143)

This *does not work correctly* whenever the Kafka client issues revoke and assign signals for the same partitions within the timeframe of `waitClosePartition`.  Whenever that happens any assigned partitions - that were marked as revoked just before - will be ignored: [SubSourceLogic.partitionAssignedCB](https://github.com/akka/alpakka-kafka/blob/v0.22/core/src/main/scala/akka/kafka/internal/SubSourceLogic.scala#L92).

**Comment by ennru** [comment]
This issue becomes visible when using manual offsets via `plainPartitionedManualOffsetSource`.

**Comment by ennru** [comment]
@tkroman Thanks for pointing this out. Yes, #590 just changed what partitions are passed to the function fetching offsets from external storage.

**Comment by Camsteack** [comment]
@ennru Thanks a lot for the quick fix

**Comment by 2m** [comment]
If you would like to try out a snapshot version with this fix merged in, we have just released a `0.22+75-ada5b3a2` to the [snapshots repo](https://doc.akka.io/docs/akka-stream-kafka/current/snapshots.html).

**Comment by Camsteack** [comment]
Will do !
