### ISSUE TITLE
Log configuration in KafkaConsumerActor preStart

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#609]
Just as the Kafka client logs its configuration the actor could dump its configuration on debug level.

**Comment by ennru** [comment]
And maybe adding `BuildInfo` and include the library version number into that log message would be a good idea.

**Comment by muditsin** [comment]
I could try to take this up. What configurations are you looking to log? the `akka.kafka.consumer` from `context.system.settings`?

**Comment by ennru** [comment]
Yes, when a Consumer stage or Producer stage is materialized it could log the `ConsumerSettings` or `ProducerSettings`. Just as Kafka consumers log their settings when started.
