### ISSUE TITLE
Stop and rerun kafka consumer after exponential backoff attempts finished

### ISSUE THREAD

**Issue by kolapkardhaval** [akka/alpakka-kafka#643]
0
down vote
favorite
I would like to consume messages. If I get exception, I will retry with exponential backoff. If that fails too, I shutdown the consumer and would like to start the consumer again after 6 hrs.

I have the following code:

    Publisher<ConsumerRecord<K, V>> source = RestartSource.onFailuresWithBackoff(
                    Duration.ofSeconds(3),
                    Duration.ofSeconds(5),
                    0.2,
                    5,
                    () -> Consumer.plainSource(
                            consumerSettings,
                            Subscriptions.topics(topic.getName()))
                            .mapMaterializedValue(
                                    c -> {
                                        control.set(c);
                                        return c;
                                    })
            ).runWith(Sink.asPublisher(AsPublisher.WITH_FANOUT),materializer);
    control.get().shutdown();
    return Flowable.fromPublisher(source);
This code does exponential backoff even it has any issue. However, I do not know how to stop the service after 5 tries, find out if it has actually stopped and then restart the consumer after 6 hrs.

**Comment by ennru** [comment]
This is more a question for the Akka forum: https://discuss.lightbend.com/c/akka/
