### ISSUE TITLE
Consumer skips fetching

### ISSUE THREAD

**Issue by dmi3zkm** [akka/alpakka-kafka#646]
Sometimes I see consumers stuck. Consumer lag grows and I see endless trace messages in logs: 
`Skipping fetch for partition topicX-N because there is an in-flight request to some-kafka-host:9092`.
According to kafka protocol there can be only one in-flight request. I guess consumer didn't get response back from broker and waits infinitely. 
Unfortunately, there are no reproduction steps yet.
Any clues and suggestions are welcome.

Kafka version - 2.0.0
Alpakka-kafka version - 0.22

**Comment by ennru** [comment]
Alpakka Kafka 0.22 uses the Kafka client of version 1.0.1, or did you overwrite it to be 2.0.0?

**Comment by dmi3zkm** [comment]
Yes, it's 1.0.1.

**Comment by dmi3zkm** [comment]
Switched to 2.0.0. Will see if it helps.

**Comment by ennru** [comment]
What kind of source and subscription do you use?

**Comment by dmi3zkm** [comment]
`Consumer.plainSource` and `AutoSubscription`.
After switching to 2.0.0 client it behaves much better I would say.

**Comment by ennru** [comment]
Interesting, the client should negotiate to agree on the protocol level.

**Comment by dmi3zkm** [comment]
Unfortunately, I can not reproduce.

**Comment by GrigorievNick** [comment]
I find simialr situation in my local test in k8s.
But also can't create reproducable steps.

**Comment by dmi3zkm** [comment]
Hey @GrigorievNick 
Have you managed to reproduce this?

**Comment by GrigorievNick** [comment]
@dmi3zkm No.
 But I work under this task during the outsourcing project, so we find a way to monitor this behavior and implement a rerun.
Right now, I don't have access to this project.
