### ISSUE TITLE
Remove deprecated API

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#680]
APIs deprecated prior to 1.0 should be removed prior to releasing 1.1 milestones.

**Comment by Philippus** [comment]
does this include deprecations marked since `1.0-RC1` or `1.0-M1` as well?

**Comment by ennru** [comment]
We'll release a 1.1 with just the upgrade to the Kafka client 2.1.1 and no other changes. So we defer removing deprecations to a later version.

**Comment by ennru** [comment]
We keep those around until 2.0 which is not too far away.

**Comment by ennru** [comment]
Fixed with #945. We leave #948 unchanged for 2.x
