### ISSUE TITLE
Commit refresh only works after consuming all messages

### ISSUE THREAD

**Issue by Philippus** [akka/alpakka-kafka#699]
I'm experiencing what I think might be an issue with refreshing offsets which was introduced in https://github.com/akka/alpakka-kafka/pull/375.
I think the commits are only refreshed if all the messages have been consumed for a _topic_ (and no new messages arrive for it). But (at least our version of) kafka expires the committed offsets per _partition_, not per _topic_.
So I can run into problems if I consumed all messages of a partition but consuming another partition takes longer than 24h or new messages keep arriving on one of the partitions, but not every partition.

Below are some partial screenshots of the consumer lag:

(intermediate state)
<img width="367" alt="schermafdruk 2019-01-07 10 57 33" src="https://user-images.githubusercontent.com/1923596/50761642-361a3a80-126b-11e9-97e4-6b77517be39c.png">

(end state)
<img width="342" alt="schermafdruk 2019-01-07 10 58 10" src="https://user-images.githubusercontent.com/1923596/50761646-387c9480-126b-11e9-9817-09a9fb61e403.png">

(after reaching the end state, I see the `Refreshing committed offsets`-message popping up in the log)

Maybe @rtimush can help to check if my reasoning is sound?

**Comment by rtimush** [comment]
I think you're right, #375 doesn't refresh offsets if there were commits even for a single partition, which may lead to the situation you described.

**Comment by Philippus** [comment]
ok, thanks for rubber ducking, I'm working on a PR for this.

**Comment by ennru** [comment]
Fixed with #701
