### ISSUE TITLE
How to correctly use DrainingControl.apply in committablesource. Can anyone please help me with an example ?

### ISSUE THREAD

**Issue by pilot-no-21** [akka/alpakka-kafka#703]
Consumer
        .committableSource(consumerSettings, Subscriptions.topics(topic))
        .mapAsync(10) { msg =>
          business(msg.record.key, msg.record.value).map(_ => msg.committableOffset)
        }
        .via(Committer.flow(committerDefaults.withMaxBatch(1)))
        .toMat(Sink.seq)(Keep.both)
        .mapMaterializedValue(DrainingControl.apply)
.run()

**Comment by 2m** [comment]
Please use [the discussion forum](https://discuss.lightbend.com/c/akka/streams-and-alpakka) for library usage questions.

The `DrainingConrol.apply` is a [function that expects](https://doc.akka.io/api/akka-stream-kafka/current/akka/kafka/scaladsl/Consumer$$DrainingControl$.html#apply[T](tuple:(akka.kafka.scaladsl.Consumer.Control,scala.concurrent.Future[T])):akka.kafka.scaladsl.Consumer.DrainingControl[T]) a tuple `(Control, Future[T])`. Make sure that is the propagated materialized value of the stream before calling `.mapMaterializedValue(DrainingControl.apply)`
