### ISSUE TITLE
KafkaConsumerActor$WrappedAutoPausedListener failed on partition assignment

### ISSUE THREAD

**Issue by Tvaroh** [akka/alpakka-kafka#716]
Hello. We've got the following errors in the log while consuming a topic. After that, no further messages could be received.

```
org.apache.kafka.common.errors.TimeoutException: Timeout of 5000ms expired before the position for partition analysis-lifecycle-0 could be determined
o.a.k.c.c.i.ConsumerCoordinator [Consumer clientId=consumer-28, groupId=analysis-lifecycle-95040282-f8ef-4458-b794-61fff901103a] User provided listener akka.kafka.internal.KafkaConsumerActor$WrappedAutoPausedListener failed on partition assignment
```

Is it a bug? What's the correct way to heal after this?

### Versions used 
Alpakka Kafka version: 1.0-RC1
Akka version: 2.5.19
Kafka version: 2.1

**Comment by ennru** [comment]
I looks like your Kafka broker is slow on responding to a `position` request. You may increase the timeout for that in `ConsumerSettings` or `application.conf`.

Please try and tell us if that works for you, I do not believe this is a bug.

**Comment by Tvaroh** [comment]
Ok, not sure about this anymore, closing.
