### ISSUE TITLE
Integration test not working with embedded server (Java)

### ISSUE THREAD

**Issue by ptitFicus** [akka/alpakka-kafka#747]
Hello, at first thank you for this great project !

I'm trying to run run exemple tests [(such as this one)](https://github.com/akka/alpakka-kafka/blob/5d4bda4612652a925f82328f7ea1d00a9ad696fd/tests/src/test/java/docs/javadsl/ProducerExampleTest.java#L82) on my own project using Java / Junit 4.

### Versions used 
Alpakka Kafka version: 1.0.1

Akka version: 2.5.21

Kafka version: embedded

### Expected Behavior

The test should complete without error.

### Actual Behavior

The test fail with a timeout while waiting for the `DrainingControl` to shutdown.

### Relevant logs

```
java.util.concurrent.TimeoutException
	at fr.ptitficus.KafkaTest.foo(KafkaTest.java:49)
```

### Reproducible Test Case

[Here is a project that reproduces the issue](https://github.com/ptitFicus/kafka-integration-test)

**Comment by ennru** [comment]
This could be due to the stop-timeout:

```
akka.kafka.consumer {
  # The stage will delay stopping the internal actor to allow processing of
  # messages already in the stream (required for successful committing).
  # Prefer use of `DrainingControl` over a large stop-timeout.
  stop-timeout = 30s
}
```

**Comment by ptitFicus** [comment]
Indeed, setting `stop-timeout` to `10ms` solve my issue, sorry, I should have looked at the test configuration.

Thank you so much.

**Comment by ennru** [comment]
It should be documented more clearly. It is quite hidden.
