### ISSUE TITLE
Static Membership support.

### ISSUE THREAD

**Issue by def1ne** [akka/alpakka-kafka#859]
### Short description

Add support of static membership in consumer.

### Details

Static membership was introduced In Kafka 2.3.0. It allows to evade rebalances if consumer group is static.

To support this feature we need to update Kafka client to 2.3.0 and add `withGroupInstanceId` function in `ConsumerSettings`.

### Links
[static membership description](https://kafka.apache.org/documentation/#static_membership)
[group.instance.id](http://kafka.apache.org/23/javadoc/org/apache/kafka/clients/consumer/ConsumerConfig.html#GROUP_INSTANCE_ID_CONFIG)
[KIP-345: Introduce static membership protocol to reduce consumer rebalances](https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances)

**Comment by ennru** [comment]
Thank you for this suggestion. Please feel free to suggest the necessary changes in a Pull Request.

**Comment by jewertow** [comment]
Since PR is merged this issue should be closed.

**Comment by ennru** [comment]
Thanks for the ping.
Fixed with #861
