### ISSUE TITLE
Add ability to resume Kafka stream after stop

### ISSUE THREAD

**Issue by SergeyIBM47** [akka/alpakka-kafka#905]
**alpakka-kafka** is a very powerful library for streaming applications but has some unpleasant limitations - stream Control has an API for stopping a stream (with `stop()` method) but doesn't have API for resuming it.

The most important features of modern applications are availability and ability continuously deliver digital solutions to the critical environment without downtime.

When we try to apply blue/green deployment approach for our services we can stop particular stream but don't have a possibility to start a stream without restarting it entirely, because `stop()` method completes an underlining stream.

I suggest to change the current `stop()` stream semantics by sending message to `KafkaConsumerActor` in order to pause a consumer but not complete a stream. And introduce a new method `resume()` to Control API that will send Resume command to KafkaConsumerActor to continue message consumption.

Could we please discuss reasonability of these features and any pitfalls.
If we agree on this I'm ready to contribute.
Thanks.

**Comment by seglo** [comment]
Hi @SergeyIBM47.  That's an interesting idea.  Before looking at designing a solution within Alpakka Kafka I would first suggest exploring the [`Valve`](https://developer.lightbend.com/docs/api/akka-stream-contrib/current/akka/stream/contrib/Valve.html) stage that exists in `akka-streams-contrib` to implement a solution that's agnostic to Alpakka Kafka.  This would allow you to produce a materialized value that can be used dynamically to toggle backpressure within the stream.  When backpressure is enabled it would effectively pause the stream.

**Comment by SergeyIBM47** [comment]
@seglo many thanks for the advice, but to resolve my problem we should have an ability to stop and resume the stream externally.

**Comment by SergeyIBM47** [comment]
@seglo many thanks for the great advice, I'm already done all explorations and tests. The [Valve ](https://developer.lightbend.com/docs/api/akka-stream-contrib/current/akka/stream/contrib/Valve.html) is highly fit for our solution. Thanks

**Comment by seglo** [comment]
@SergeyIBM47 You're welcome.  I'm glad it fit your use case.
