### ISSUE TITLE
User-defined seeking for subscriptions

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#911]
### Short description

It might be useful to allow access to the `RestrictedConsumer` when subscribing so that special seeking can be achieved (eg. seek-to-beginning).

### Details

The subscription would be enhanced to send in a function `(Set[TopicPartition], RestrictedConsumer) => Unit` so that the user may pass it for their need to seek to a specific position before any data is received. That function would be applied when the first `onPartitionsAssigned` is called from the Kafka client.

**Comment by jewertow** [comment]
I would like to do it. I could prepare PR within 1-2 weeks.

**Comment by ennru** [comment]
This can now be implemented by the user by leveraging the `PartitionAssignmentHandler` added in #949
