### ISSUE TITLE
Testkit: Allow users to pass broker configuration to test containers

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#933]
### Short description

Allow the user to pass arbitrary Kafka broker config to test containers managed by the testkit.

### Details

Test containers allows users to configure the underlying service using environment variables.  Kafka broker configuration can be overridden with environment variables, so it would be useful to allow users to provide arbitrary config to the test container before it starts up.

On a related note, the test container will only start up once for the entire test suite.  Is there a way to configure test containers to spin up per test class, or test method, each with its own config?

**Comment by ennru** [comment]
This was made possible with #939.
