### ISSUE TITLE
Alpakka Kafka 2.0 plans

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#940]
Apache Kafka 2.4.0 is scheduled for the end of October 2019 and we plan to release Alpakka Kafka 2.0 shortly after. This dependency update to Kafka 2.4.0 is the main reason to call out a new major version.

But we hope to get in new features, as well:
* Partitioned transactional sources
* built-in Akka Discovery support

Please have a look at the [2.0.0-M1 milestone](https://github.com/akka/alpakka-kafka/milestone/34) and [2.0.0-RC1 milestone](https://github.com/akka/alpakka-kafka/milestone/39) to see what we hope to get done before.
A few Pull Request that would be part of 1.1.1 are merged already and will go into 2.0.0, as well. See the [1.1.1 milestone](https://github.com/akka/alpakka-kafka/issues?utf8=%E2%9C%93&q=milestone%3A1.1.1).

**Comment by ennru** [comment]
[Kafka Release Plan 2.4.0](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=125307901)

**Comment by ennru** [comment]
Kafka 2.4.0 build https://github.com/akka/alpakka-kafka/pull/971

**Comment by seglo** [comment]
Revert Apache Staging maven repo before release https://github.com/akka/alpakka-kafka/issues/983

**Comment by ennru** [comment]
We'll release Alpakka Kafka 2.0.0-M1 with the 2.4.0-RC1 Kafka client.

**Comment by ennru** [comment]
We intend to release Alpakka Kafka 2.0.0 shortly.
See #1015
