### ISSUE TITLE
Replace remaining embedded Kafka tests with testcontainers and mark embedded Kafka as provided

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#950]
### Short description

Using testcontainers decouples our testsuite from having to depend on embedded Kafka/ZooKeeper and all the transient dependencies they bring.  Let's replace the remaining tests that use embedded Kafka to use testcontainers.

### Details

Identify all internal tests that mix in the `EmbeddedKafkaLike` trait and replace them with the appropriate testcontainers mix implementation.  Next, mark the embedded Kafka dependencies as optional for the testkit, and drop them from our tests project.

**Comment by ennru** [comment]
I guess we'd like to leave some that show how to use `EmbeddedKafkaLike` things for the docs.

**Comment by seglo** [comment]
That's true, though it does negate the advantage of not managing the dependency.

**Comment by ennru** [comment]
Fixed with #954
