### ISSUE TITLE
Consumer drops records after rebalance

### ISSUE THREAD

**Issue by altomch** [akka/alpakka-kafka#978]
### Versions used 

Akka version: 2.5.23
Alpakka-Kafka version: 1.1.0
Scala version: 2.12.10

### Expected Behavior

Committable Consumer shouldn't loose any record consumed from Kafka 

### Actual Behavior

We observed that after rebalance some records were dropped out from processing, exactly the same behavior that was described by @vlovgr in [#336](https://github.com/akka/alpakka-kafka/issues/336#issuecomment-410738395), we've lost 500 records from topic, it was very clear because we've consumed the data from the beginning of topic and we didn't observe any result from those records (no logs, no state changes).

### Reproducible Test Case

After deep diving into code I've end up with opening bug for  [Scala - #11807](https://github.com/scala/bug/issues/11807).

This bug causes misbehavior when records are consumed from Kafka but concatenated to broken buffer [`BaseSingleSourceLogic`](https://github.com/akka/alpakka-kafka/blob/master/core/src/main/scala/akka/kafka/internal/BaseSingleSourceLogic.scala#L60).

**Comment by ennru** [comment]
Thank you for diving into this and reporting it to the Scala issue tracker. We'll try to find a work-around for the upcoming release.

**Comment by seglo** [comment]
Nice find :+1:

**Comment by altomch** [comment]
Seems SubSourceLogic doesn't suffer from this issue.
SubSourceStage requests only one TopicPartition, so KafkaConsumeActor will never concatenate messages.

**Comment by ennru** [comment]
We plan to release Alpakka Kafka 2.0.0-M1 #988 now and can't wait for new Scala version of 2.12 and 2.13.
To avoid hitting the `ConcatIterator` bug I created #997.

**Comment by ennru** [comment]
Fixed for now with #997.
The fix targetting Scala 2.13.2 was merged, as well.
