### ISSUE TITLE
Docs: add samples for creating `KafkaConsumerActor` for typed actor systems

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#984]
The Alpakka Kafka documentation should show how the classic `KafkaConsumerActor` is created when the user has a typed actor system.

**Comment by johanandren** [comment]
Is there something more to it than adapting the system with `.toClassic` ?

**Comment by ennru** [comment]
Not really, but still relevant to show, I believe.
The work is more to put that into compiling code for Alpakka Kafka docs.

**Comment by johanandren** [comment]
If you update to require Akka 2.5.27 you can have the methods take an `ClassicActorSystemProvider` and that will make it possible to pass both typed and classic actor systems.

**Comment by johanandren** [comment]
No, sorry, we never back ported that, scratch last comment.

**Comment by ennru** [comment]
Now that we have a module which is compiled only with Akka 2.6, this is much easier to add.

**Comment by seglo** [comment]
It's a bit of a franken-module though.  It's not included in the rest of the build so that it doesn't pull up Akka 2.6 deps inadvertently.  Once 2.5 support is dropped it will be reintegrated, but for now the only place to add such a code example would be in the module itself, which may be fine, in the meantime.

**Comment by seglo** [comment]
Deferring until 2.1.0

**Comment by ennru** [comment]
Once #1209 is merged, we should review the doc examples and consider primarily showing the new actors API in the docs.

**Comment by seglo** [comment]
Implemented in #1370.
