### ISSUE TITLE
Kafka Consumer stuck trying to connect to unreachable Kafka broker

### ISSUE THREAD

**Issue by politrons** [akka/alpakka-kafka#987]
Hi all,

I just update my project from `Akka-kafka-stream` `0.22` to `1.0.0` and I see that now with the new version there's no `MaxWakeUps` attribute to configure.

My problem is, that my connector it should try to connect to Kafka, and after some attempts it should continue his execution, since is doing more actions. But now after update, it got stuck forever trying to connect, and the rest of my Actor is not initialized, getting stuck.

Any way to unlock the creation of the Actor when it tries to connect to Kafka?.

Regards.

**Comment by ennru** [comment]
Check out the `ConnectionChecker`

https://github.com/akka/alpakka-kafka/blob/7967fb08935151dadc2940032219b49187ed2b51/core/src/main/resources/reference.conf#L127-L144

**Comment by politrons** [comment]
@ennru Thanks I will try that

**Comment by ennru** [comment]
I hope this solved your problem.
An addition to the docs might be useful.

**Comment by rahulkhanna2** [comment]
Were you able to use it because when I tried the Connection Checker, the consumer did poll the broker indefinitely  even when broker was not available


`    
     val checker = ConnectionCheckerSettings(2, 10.seconds, 2)
    
     val consumerSettings = ConsumerSettings(system, new StringDeserializer, new StringDeserializer)
      .withBootstrapServers(bootstrapServer)
      .withGroupId(consumerGroup)
      .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest")
      .withProperty(ENABLE_AUTO_COMMIT_CONFIG, "false")
      .withProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000")
      .withProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000")
      .withProperty("connections.max.idle.ms", "900000")
      .withProperty("request.timeout.ms", "90000")
      .withConnectionChecker(checker)

    Consumer.committableSource(consumerSettings, Subscriptions.topics(kafkaTopic))`
    
   Can someone explain what's wrong, because I don't see any useful example in docs as well
